### PR TITLE
Create Hey.md

### PR DESCRIPTION
**Pull request by LasymAndIris**

### CODE REVIEW

**Review by MaelImhof — COMMENTED** [review]
Why would you create a document called Hey.md tho?

**Comment by LasymAndIris** [comment]
I mean it's a pretty good idea isn't it?

**Review by MaelImhof — CHANGES_REQUESTED** [review]
Yeah please change the name to Hello.md, Hey.md does not suit me

**Comment by LasymAndIris** [comment]
Right let's say it's done

**Review by MaelImhof — APPROVED** [review]
Okok good enough for me

**Pull request merged**
